/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cafesystem;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nathan
 */
public class EmployeeList1 extends javax.swing.JInternalFrame {

    /**
     * Creates new form EmployeeList1
     */
    public EmployeeList1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmloyeeList = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        btnDelate = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnsearch = new javax.swing.JButton();
        cmbempid = new javax.swing.JComboBox();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("                                                           Employee List");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        tblEmloyeeList.setBackground(new java.awt.Color(153, 255, 153));
        tblEmloyeeList.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 204)));
        tblEmloyeeList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Emp ID", "First Name", "Last Name", "Sex", "Salary", "Date of Birth"
            }
        ));
        jScrollPane1.setViewportView(tblEmloyeeList);

        btnRefresh.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(255, 0, 204));
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnNew.setFont(new java.awt.Font("Noto Sans", 3, 18)); // NOI18N
        btnNew.setForeground(java.awt.Color.magenta);
        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnDelate.setFont(new java.awt.Font("Noto Sans", 3, 18)); // NOI18N
        btnDelate.setForeground(java.awt.Color.magenta);
        btnDelate.setText("Delete");
        btnDelate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelateActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Noto Sans", 3, 18)); // NOI18N
        btnUpdate.setForeground(java.awt.Color.magenta);
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 255));
        jLabel1.setText("Enter EmployeeID:");

        btnsearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnsearch.setForeground(new java.awt.Color(204, 0, 255));
        btnsearch.setText("Search");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        cmbempid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbempid.setForeground(new java.awt.Color(204, 0, 255));
        cmbempid.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(cmbempid, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnsearch)
                .addGap(45, 45, 45)
                .addComponent(btnNew)
                .addGap(18, 18, 18)
                .addComponent(btnDelate)
                .addGap(18, 18, 18)
                .addComponent(btnUpdate)
                .addGap(18, 18, 18)
                .addComponent(btnRefresh))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDelate, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(btnsearch)
                        .addComponent(cmbempid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        readEmployee();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        insertEmployee();
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnDelateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelateActionPerformed
        // TODO add your handling code here:
        deleteEmployee();
    }//GEN-LAST:event_btnDelateActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        updateEmployee();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:

        Connection conn = null;
        PreparedStatement pst = null;
        ResultSet rst = null;
        String sql = "Select * from employee where Employee_ID = ?";
        DefaultTableModel EmployeeTblModel = (DefaultTableModel) tblEmloyeeList.getModel();
        EmployeeTblModel.setRowCount(0);
        try {
            conn = ConnectToDB.getConnected();
            pst = conn.prepareStatement(sql);
            pst.setInt(1, Integer.parseInt(cmbempid.getSelectedItem().toString()));
            rst = pst.executeQuery();

            while (rst.next()) {
                EmployeeTblModel.addRow(new Object[]{rst.getString("First_Name"), rst.getString("Last_Name"), rst.getString("Sex"), rst.getDouble("Salary"), rst.getDate("dateOfBirth")});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Database server error" + e.getMessage());

        }
    }//GEN-LAST:event_btnsearchActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        getEmployeeList1();
    }//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelate;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnsearch;
    private javax.swing.JComboBox cmbempid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEmloyeeList;
    // End of variables declaration//GEN-END:variables
    Connection conn = null;
    Statement stmt = null;
    ResultSet rst = null;

    private void readEmployee() {

        DefaultTableModel EmployeeTblModel = (DefaultTableModel) tblEmloyeeList.getModel();
        EmployeeTblModel.setRowCount(0);
        String sql = "Select * From employee order by employee_ID ASC";
        try {
            conn = ConnectToDB.getConnected();
            stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            rst = stmt.executeQuery(sql);
            int row = 0;
            while (rst.next()) {
                EmployeeTblModel.addRow(new Object[]{rst.getString("employee_ID"), rst.getString("First_Name"), rst.getString("Last_Name"), rst.getString("Sex"), rst.getDouble("Salary"), rst.getDate("dateOfBirth")});
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Database server error" + e.getMessage());
        }
    }

    private void insertEmployee() {
        DefaultTableModel EmployeeTblModel = (DefaultTableModel) tblEmloyeeList.getModel();
        if (btnNew.getText().equalsIgnoreCase("New")) {
            int emptrow = EmployeeTblModel.getRowCount() + 1;
            EmployeeTblModel.setRowCount(emptrow);
            btnNew.setText("Save");
        } else {
            int newrow = EmployeeTblModel.getRowCount() - 1;
            try {

                rst.moveToInsertRow();
                rst.updateString("Employee_Id", EmployeeTblModel.getValueAt(newrow, 0).toString());
                rst.updateString("First_Name", EmployeeTblModel.getValueAt(newrow, 1).toString());
                rst.updateString("Last_Name", EmployeeTblModel.getValueAt(newrow, 2).toString());
                rst.updateString("Sex", EmployeeTblModel.getValueAt(newrow, 3).toString());
                rst.updateString("Salary", EmployeeTblModel.getValueAt(newrow, 4).toString());
//                rst.updateString("Date Of Birth", EmployeeTblModel.getValueAt(newrow, 5).toString());
                rst.insertRow();
                rst.moveToCurrentRow();
                JOptionPane.showMessageDialog(this, "Record saved successfully.");
                btnNew.setText("New");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Database server error" + e.getMessage());
            }
        }
    }

    private void updateEmployee() {
        DefaultTableModel EmployeeTblModel = (DefaultTableModel) tblEmloyeeList.getModel();
        try {
            int resp = JOptionPane.showConfirmDialog(this, "Are you sure you want to update the selected record?");
            if (resp == JOptionPane.YES_OPTION) {
                int row = tblEmloyeeList.getSelectedRow() + 1;
                rst.absolute(row);
                rst.updateString("Employee_Id", EmployeeTblModel.getValueAt(tblEmloyeeList.getSelectedRow(), 0).toString());
                rst.updateString("First_Name", EmployeeTblModel.getValueAt(tblEmloyeeList.getSelectedRow(), 1).toString());
                rst.updateString("Last_Name", EmployeeTblModel.getValueAt(tblEmloyeeList.getSelectedRow(), 2).toString());
                rst.updateString("Sex", EmployeeTblModel.getValueAt(tblEmloyeeList.getSelectedRow(), 3).toString());
                rst.updateString("Salary", EmployeeTblModel.getValueAt(tblEmloyeeList.getSelectedRow(), 4).toString());
                rst.updateRow();
                JOptionPane.showMessageDialog(this, "Record updated successfully.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Database server error" + e.getMessage());
        }
    }

    private void deleteEmployee() {
        try {
            int resp = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete the selected record?");
            if (resp == JOptionPane.YES_OPTION) {
                int row = tblEmloyeeList.getSelectedRow() + 1;
                rst.absolute(row);
                rst.deleteRow();
                JOptionPane.showMessageDialog(this, "Record deleted successfully.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Database server error" + e.getMessage());
        }
    }

    private void getEmployeeList1() {

        Connection conn = null;
        Statement stmt = null;
        ResultSet rst = null;
        String sql = "Select *From employee order by Employee_ID ASC";
        try {
            conn = ConnectToDB.getConnected();
            stmt = conn.createStatement();
            rst = stmt.executeQuery(sql);
            while (rst.next()) {

                int fcode = rst.getInt("Employee_ID");
                String fname = rst.getString("Employee_ID");
                ComboBoxItem fitem = new ComboBoxItem(fcode, fname);
                cmbempid.addItem(fitem);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Database server error" + e.getMessage());
        }
    }
}
