/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cafesystem;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nathan
 */
public class MealProgramList extends javax.swing.JInternalFrame {

    /**
     * Creates new form MealProgramList
     */
    public MealProgramList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblMealprogram = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        btnDelate = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cmbProgramcode = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(204, 204, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("                                                   meal program  List");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        tblMealprogram.setBackground(new java.awt.Color(204, 204, 204));
        tblMealprogram.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 2));
        tblMealprogram.setForeground(new java.awt.Color(255, 0, 204));
        tblMealprogram.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MealDate", "MealType", "MealStatus"
            }
        ));
        jScrollPane2.setViewportView(tblMealprogram);

        btnRefresh.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(204, 0, 204));
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnNew.setFont(new java.awt.Font("Noto Sans", 3, 18)); // NOI18N
        btnNew.setForeground(java.awt.Color.magenta);
        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnDelate.setFont(new java.awt.Font("Noto Sans", 3, 18)); // NOI18N
        btnDelate.setForeground(java.awt.Color.magenta);
        btnDelate.setText("Delete");
        btnDelate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelateActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Noto Sans", 3, 18)); // NOI18N
        btnUpdate.setForeground(java.awt.Color.magenta);
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnSearch.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 0, 204));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 153));
        jLabel1.setText("Enter Meal Program code:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbProgramcode, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNew)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDelate, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRefresh)))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnNew, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDelate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(cmbProgramcode, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(btnRefresh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        readMealProgram();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        insertMealProgram();
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnDelateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelateActionPerformed
        // TODO add your handling code here:
        deleteMealProgram();
    }//GEN-LAST:event_btnDelateActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        updateMealProgram();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        Connection conn = null;
        PreparedStatement pst = null;
        ResultSet rst = null;
        String sql = "Select * from meal_program where meal_programCode = ?";
        DefaultTableModel MealProgramTblModel = (DefaultTableModel) tblMealprogram.getModel();
        MealProgramTblModel.setRowCount(0);
        try {
            conn = ConnectToDB.getConnected();
            pst = conn.prepareStatement(sql);
            pst.setInt(1, Integer.parseInt(cmbProgramcode.getSelectedItem().toString()));
            rst = pst.executeQuery();

            while (rst.next()) {
                MealProgramTblModel.addRow(new Object[]{rst.getInt("meal_programCode"), rst.getDate("Meal_Date"), rst.getString("Meal_Type"), rst.getString("Meal_Status")});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Database server error" + e.getMessage());

        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        getMealProgramList();
    }//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelate;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox cmbProgramcode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblMealprogram;
    // End of variables declaration//GEN-END:variables
        Connection conn = null;
    Statement stmt = null;
    ResultSet rst = null;

    private void readMealProgram() {

        DefaultTableModel MealProgramTblModel = (DefaultTableModel) tblMealprogram.getModel();
        MealProgramTblModel.setRowCount(0);
        String sql = "Select * From Meal_Program order by meal_programCode ASC";
        try {
            conn = ConnectToDB.getConnected();
            stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            rst = stmt.executeQuery(sql);
            int row = 0;
            while (rst.next()) {
                MealProgramTblModel.addRow(new Object[]{rst.getDate("Meal_Date"), rst.getString("Meal_Type"), rst.getString("Meal_Status")});
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Database server error" + e.getMessage());
        }
    }

    private void insertMealProgram() {
        DefaultTableModel MealProgramTblModel = (DefaultTableModel) tblMealprogram.getModel();
        if (btnNew.getText().equalsIgnoreCase("New")) {
            int emptrow = MealProgramTblModel.getRowCount() + 1;
            MealProgramTblModel.setRowCount(emptrow);
            btnNew.setText("Save");
        } else {
            int newrow = MealProgramTblModel.getRowCount() - 1;
            try {

                rst.moveToInsertRow();

//                rst.updateString("Meal_ProgramCode", MealProgramTblModel.getValueAt(newrow, 0).toString());
                rst.updateString("Meal_Date", MealProgramTblModel.getValueAt(newrow, 0).toString());
                rst.updateString("Meal_Type", MealProgramTblModel.getValueAt(newrow, 1).toString());
                rst.updateString("Meal_Status", MealProgramTblModel.getValueAt(newrow, 2).toString());
                rst.insertRow();
                rst.moveToCurrentRow();
                JOptionPane.showMessageDialog(this, "Record saved successfully.");
                btnNew.setText("New");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Database server error" + e.getMessage());
            }
        }
    }

    private void updateMealProgram() {
        DefaultTableModel MealProgramTblModel = (DefaultTableModel) tblMealprogram.getModel();
        try {
            int resp = JOptionPane.showConfirmDialog(this, "Are you sure you want to update the selected record?");
            if (resp == JOptionPane.YES_OPTION) {
                int row = tblMealprogram.getSelectedRow() + 1;
                rst.absolute(row);
//                rst.updateString("Meal_ProgramCode", MealProgramTblModel.getValueAt(tblMealprogram.getSelectedRow(), 0).toString());
                rst.updateString("Meal_Date", MealProgramTblModel.getValueAt(tblMealprogram.getSelectedRow(), 0).toString());
                rst.updateString("Meal_Type", MealProgramTblModel.getValueAt(tblMealprogram.getSelectedRow(), 1).toString());
                rst.updateString("Meal_Status", MealProgramTblModel.getValueAt(tblMealprogram.getSelectedRow(), 2).toString());
                rst.updateRow();
                JOptionPane.showMessageDialog(this, "Record updated successfully.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Database server error" + e.getMessage());
        }
    }

    private void deleteMealProgram() {
        try {
            int resp = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete the selected record?");
            if (resp == JOptionPane.YES_OPTION) {
                int row = tblMealprogram.getSelectedRow() + 1;
                rst.absolute(row);
                rst.deleteRow();
                JOptionPane.showMessageDialog(this, "Record deleted successfully.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Database server error" + e.getMessage());
        }
    }

    private void getMealProgramList() {
        Connection conn = null;
        Statement stmt = null;
        ResultSet rst = null;
        String sql = "Select *From meal_program order by meal_programCode ASC";
        try {
            conn = ConnectToDB.getConnected();
            stmt = conn.createStatement();
            rst = stmt.executeQuery(sql);
            while (rst.next()) {

                int fcode = rst.getInt("meal_programCode");
                String fname = rst.getString("meal_programCode");
                ComboBoxItem fitem = new ComboBoxItem(fcode, fname);
                cmbProgramcode.addItem(fitem);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Database server error" + e.getMessage());
        }
    }
}
