/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cafesystem;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nathan
 */
public class StudentList1 extends javax.swing.JInternalFrame {

    /**
     * Creates new form StudentList1
     */
    public StudentList1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudentList = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        btnDelate = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        Jlabel = new javax.swing.JLabel();
        btnsearch = new javax.swing.JButton();
        cmbstudentID = new javax.swing.JComboBox();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("                                                      Student List");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        tblStudentList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student_ID", "FirstName", "LastName", "MealCardID", "Sex", "Department", "Year", "DateOfbirth"
            }
        ));
        jScrollPane1.setViewportView(tblStudentList);

        btnRefresh.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(102, 0, 153));
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnNew.setFont(new java.awt.Font("Noto Sans", 3, 18)); // NOI18N
        btnNew.setForeground(new java.awt.Color(102, 0, 153));
        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnDelate.setFont(new java.awt.Font("Noto Sans", 3, 18)); // NOI18N
        btnDelate.setForeground(new java.awt.Color(102, 0, 153));
        btnDelate.setText("Delete");
        btnDelate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelateActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Noto Sans", 3, 18)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(102, 0, 153));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        Jlabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Jlabel.setForeground(new java.awt.Color(204, 51, 255));
        Jlabel.setText("ENTER StudentID:");

        btnsearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnsearch.setForeground(new java.awt.Color(102, 0, 153));
        btnsearch.setText("Search");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        cmbstudentID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbstudentID.setForeground(new java.awt.Color(204, 51, 255));
        cmbstudentID.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        cmbstudentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbstudentIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addComponent(Jlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmbstudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnsearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNew)
                .addGap(18, 18, 18)
                .addComponent(btnDelate)
                .addGap(18, 18, 18)
                .addComponent(btnUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRefresh))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDelate, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnsearch)
                            .addComponent(cmbstudentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Jlabel))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        readStudentRegister();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        insertStudentRegister();
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnDelateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelateActionPerformed
        // TODO add your handling code here:
        deleteStudentRegister();
    }//GEN-LAST:event_btnDelateActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        updateStudentRegister();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:

        Connection conn = null;
        PreparedStatement pst = null;
        ResultSet rst = null;
        String sql = "Select * from student where student_id = ?";
        DefaultTableModel StudentTblModel = (DefaultTableModel) tblStudentList.getModel();
        StudentTblModel.setRowCount(0);
        try {
            conn = ConnectToDB.getConnected();
            pst = conn.prepareStatement(sql);
            pst.setInt(1, Integer.parseInt(cmbstudentID.getSelectedItem().toString()));
            rst = pst.executeQuery();

            while (rst.next()) {
                StudentTblModel.addRow(new Object[]{rst.getInt("student_id"), rst.getString("First_Name"), rst.getString("Last_Name"), rst.getInt("Meal_Card_ID"), rst.getString("Sex"), rst.getString("Department"), rst.getString("Year"), rst.getDate("dateOfBirth")});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Database server error" + e.getMessage());

        }

    }//GEN-LAST:event_btnsearchActionPerformed

    private void cmbstudentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbstudentIDActionPerformed
        // TODO add your handling code here:
//        getStudentList();
    }//GEN-LAST:event_cmbstudentIDActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
//        getStudentList();
    }//GEN-LAST:event_formMouseClicked

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        getStudentList();
    }//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jlabel;
    private javax.swing.JButton btnDelate;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnsearch;
    private javax.swing.JComboBox cmbstudentID;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblStudentList;
    // End of variables declaration//GEN-END:variables
    Connection conn = null;
    Statement stmt = null;
    ResultSet rst = null;

    private void readStudentRegister() {
        
        DefaultTableModel StudentTblModel = (DefaultTableModel) tblStudentList.getModel();
        StudentTblModel.setRowCount(0);
        String sql = "Select * From Student order by student_id ASC";
        try {
            conn = ConnectToDB.getConnected();
            stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            rst = stmt.executeQuery(sql);
            int row = 0;
            while (rst.next()) {
                StudentTblModel.addRow(new Object[]{rst.getInt("student_id"), rst.getString("First_Name"), rst.getString("Last_Name"), rst.getInt("Meal_Card_ID"), rst.getString("Sex"), rst.getString("Department"), rst.getString("Year"), rst.getDate("dateOfBirth")});
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Database server error" + e.getMessage());
        } 
    }

    private void insertStudentRegister() {
        DefaultTableModel StudentTblModel = (DefaultTableModel) tblStudentList.getModel();
        if (btnNew.getText().equalsIgnoreCase("New")) {
            int emptrow = StudentTblModel.getRowCount() + 1;
            StudentTblModel.setRowCount(emptrow);
            btnNew.setText("Save");
        } else {
            int newrow = StudentTblModel.getRowCount() - 1;
            try {

                rst.moveToInsertRow();

                rst.updateString("student_id", StudentTblModel.getValueAt(newrow, 0).toString());
                rst.updateString("First_Name", StudentTblModel.getValueAt(newrow, 1).toString());
                rst.updateString("Last_Name", StudentTblModel.getValueAt(newrow, 2).toString());
                rst.updateString("Meal_Card_ID", StudentTblModel.getValueAt(newrow, 3).toString());
                rst.updateString("Sex", StudentTblModel.getValueAt(newrow, 4).toString());
                rst.updateString("Department", StudentTblModel.getValueAt(newrow, 5).toString());
                rst.updateString("Year", StudentTblModel.getValueAt(newrow, 6).toString());
                rst.updateString("dateOfBirth", StudentTblModel.getValueAt(newrow, 7).toString());
                rst.insertRow();
                rst.moveToCurrentRow();
                JOptionPane.showMessageDialog(this, "Record saved successfully.");
                btnNew.setText("New");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Database server error" + e.getMessage());
            }
        }
    }

    private void updateStudentRegister() {
        DefaultTableModel StudentTblModel = (DefaultTableModel) tblStudentList.getModel();
        try {
            int resp = JOptionPane.showConfirmDialog(this, "Are you sure you want to update the selected record?");
            if (resp == JOptionPane.YES_OPTION) {
                int row = tblStudentList.getSelectedRow() + 1;
                rst.absolute(row);
                rst.updateString("student_id", StudentTblModel.getValueAt(tblStudentList.getSelectedRow(), 0).toString());
                rst.updateString("First_Name", StudentTblModel.getValueAt(tblStudentList.getSelectedRow(), 1).toString());
                rst.updateString("Last_Name", StudentTblModel.getValueAt(tblStudentList.getSelectedRow(), 2).toString());
                rst.updateString("Meal_Card_ID", StudentTblModel.getValueAt(tblStudentList.getSelectedRow(), 3).toString());
                rst.updateString("Sex", StudentTblModel.getValueAt(tblStudentList.getSelectedRow(), 4).toString());
                rst.updateString("Department", StudentTblModel.getValueAt(tblStudentList.getSelectedRow(), 5).toString());
                rst.updateString("Year", StudentTblModel.getValueAt(tblStudentList.getSelectedRow(), 6).toString());
                rst.updateString("dateOfBirth", StudentTblModel.getValueAt(tblStudentList.getSelectedRow(), 7).toString());
                rst.updateRow();
                JOptionPane.showMessageDialog(this, "Record updated successfully.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Database server error" + e.getMessage());
        }
    }

    private void deleteStudentRegister() {
        try {
            int resp = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete the selected record?");
            if (resp == JOptionPane.YES_OPTION) {
                int row = tblStudentList.getSelectedRow() + 1;
                rst.absolute(row);
                rst.deleteRow();
                JOptionPane.showMessageDialog(this, "Record deleted successfully.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Database server error" + e.getMessage());
        }
    }

    private void getStudentList() {
        Connection conn = null;
        Statement stmt = null;
        ResultSet rst = null;
        String sql = "Select *From student order by student_ID ASC";
        try {
            conn = ConnectToDB.getConnected();
            stmt = conn.createStatement();
            rst = stmt.executeQuery(sql);
            while (rst.next()) {

                int fcode = rst.getInt("student_id");
                String fname = rst.getString("student_id");
                ComboBoxItem fitem = new ComboBoxItem(fcode, fname);
                cmbstudentID.addItem(fitem);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Database server error" + e.getMessage());
        }
    }
}
